import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Retriever accuracy tests — validate that brute-force cosine similarity
 * in TypeScript produces the same results as ChromaDB in Python.
 *
 * These tests load the pre-computed chunks and compare against the ground
 * truth generated by scripts/generate_ground_truth.py. The embedding model
 * must be downloaded for these to run (first `pnpm build && node dist/index.js`).
 *
 * For CI without the model, the guardrails tests provide basic coverage.
 */

interface GroundTruthEntry {
  query: string;
  top_5: Array<{
    id: string;
    score: number;
    book: number;
    chapter: number;
  }>;
}

// Load ground truth fixture
const groundTruth: GroundTruthEntry[] = JSON.parse(
  readFileSync(join(__dirname, "fixtures", "retrieval_ground_truth.json"), "utf-8"),
);

describe("retriever", () => {
  // This test validates data integrity without needing the HF model
  it("should have ground truth with expected structure", () => {
    expect(groundTruth.length).toBe(8);
    for (const entry of groundTruth) {
      expect(entry.query).toBeTruthy();
      expect(entry.top_5).toHaveLength(5);
      for (const result of entry.top_5) {
        expect(result.id).toMatch(/^nic_eth_b\d+_c\d+_\d+$/);
        expect(result.score).toBeGreaterThan(0);
        expect(result.score).toBeLessThanOrEqual(1);
        expect(result.book).toBeGreaterThan(0);
        expect(result.chapter).toBeGreaterThan(0);
      }
    }
  });

  it("should have chunks_with_embeddings.json with correct structure", () => {
    const chunks = JSON.parse(
      readFileSync(join(__dirname, "..", "data", "chunks_with_embeddings.json"), "utf-8"),
    );
    expect(chunks.length).toBe(187);
    const first = chunks[0];
    expect(first.id).toBeTruthy();
    expect(first.text).toBeTruthy();
    expect(first.embedding).toHaveLength(384);
    expect(typeof first.book).toBe("number");
    expect(typeof first.chapter).toBe("number");
    expect(Array.isArray(first.tags)).toBe(true);
  });

  it("ground truth top scores should be above MIN_RELEVANCE_SCORE for on-topic queries", () => {
    const MIN_RELEVANCE_SCORE = 0.25;
    for (const entry of groundTruth) {
      const topScore = entry.top_5[0].score;
      expect(topScore).toBeGreaterThan(MIN_RELEVANCE_SCORE);
    }
  });
});
